### ISSUE TITLE
User closes browser, how to know the payment is being processed?

### ISSUE THREAD

**Issue by AntonPetrov83** [xsolla/store-unity-sdk#66]
The problem is a user starts a purchase but I do not know if it will be finished at all because user can simply close the browser and no success neither error calbacks get called. So the game thinks a purchase is pending forever.

**Comment by DenisRakhimovXsolla** [comment]
> The problem is a user starts a purchase but I do not know if it will be finished at all because user can simply close the browser and no success neither error calbacks get called. So the game thinks a purchase is pending forever.

**Comment by DenisRakhimovXsolla** [comment]
Hey @AntonPetrov83 !

Please take a look - these methods have an `onBrowserClosed` parameter that covers this case. You can pass a callback that will be called after the browser is closed and handle this event in your code
- [XsollaCatalog.Purchase](https://github.com/xsolla/store-unity-sdk/blob/ac203ecb943ee6af6d5aa01eb0e056658b542c4a/Assets/Xsolla/Catalog/XsollaCatalog.cs#L402)
- [‎XsollaWebBrowser.OpenPurchaseUI](https://github.com/xsolla/store-unity-sdk/blob/ac203ecb943ee6af6d5aa01eb0e056658b542c4a/Assets/Xsolla/Core/Browser/XsollaWebBrowser.cs#L44C1-L45C1)

**Comment by AntonPetrov83** [comment]
Hey @DenisRakhimovXsolla 

This problem introduces a leak into Xsolla SDK - see details below.

I know about `onBrowserClosed` callback.

The problem is a user can close the browser BEFORE initiating a payment ot AFTER.

1. If a user closes browser BEFORE initiating a payment - no other callbacks get called (no `onSuccess`, no `onError`)
2. If a user closes browser AFTER initiating a payment - one of callbacks will be invoked later.

This problem introduces a leak into Xsolla SDK.

If you open browser and the close it multiple times then you will end up with multiple instances of `OrderTracker` instances spinning forever.

**Comment by DenisRakhimovXsolla** [comment]
@AntonPetrov83 
Thank you for description.
Please clarify what do you mean by `initiating a payment`?

**Comment by AntonPetrov83** [comment]
@DenisRakhimovXsolla 
I mean pressing this blue button in the browser "Pay $0.99" (as an example).

**Comment by DenisRakhimovXsolla** [comment]
@AntonPetrov83 
And after that you just call `XsollaCatalog.Purchase`, right?
Not working directly with any orders, browsers, etc?

**Comment by AntonPetrov83** [comment]
@DenisRakhimovXsolla 
Sorry I do not understand.
1. I call `XsollaCatalog.Purchase`
2. The browser opens
3. I push the "Pay" button or I do not.
4. I close the browser.
5. onBrowserClosed callback gets invoked with `isManually` = `true`
6. `onSuccess` callback will be called or won't dependent on my action in step 3.

**Comment by DenisRakhimovXsolla** [comment]
Hey @AntonPetrov83 !
Ok, let's split the problem into technical and business:

1. Technical
A leak is not really a leak, it's kind of a part of the overall business logic.
Because SDK provides the ability to open the payment interface in an external browser - it is possible to open several payments at the same time (in several browser tabs) and make a purchase after some unknown amount of time and the game must track this purchase and respond to it - that's why we don't stop tracking the order, and the trackers work conditionally indefinitely (in fact, around 15 minutes). This is not your case as I understand it, but this is part of the general functionality of the SDK. There are ways to improve, of course, but for now we have a more priority tasks.

2. Business
There are many different scenarios here, let's be specific:
- What platform? Web, mobile, desktop?
- Is the “Enable In-App Browser” option enabled in the SDK settings?
- Do you use some of the redirect condition option (automatic or manual)  from the redirect policy settings?

<img width="929" alt="image" src="https://github.com/xsolla/store-unity-sdk/assets/82079211/2324b229-f26d-4010-9d6b-d5ffe82dd269">

**Comment by AntonPetrov83** [comment]
@DenisRakhimovXsolla Hi!

Our major platform for using Xsolla is Android. I do development and inital testing in the Unity Editor with the built-in Xsolla browser.

In-App Browser is enabled, Yes.

I do not use redirect policies.
